% Generate matrices for LIMO comparison
% 1. Get the setsize wise graph theory parameter matrix
% 2. Get Below, Opt, Above
% 3. Create one dataset from only PREWM for LIMO stats
% 4. We would need to do params*bands and see the topos
% SCZ plots

% author @ Rahul Venugopal on July 26, 2023

% Load the master data
load robust_t_paired_prewm_th33.mat;
% Load the chanlocs file
load chanlocs_55.mat;

%% LIMO stats
condnlist  = {...
    'Opt vs Below | Clustering | Theta';...
    'Opt vs Below | Clustering | Alpha';...
    'Opt vs Below | Clustering | Beta';...
    'Opt vs Below | Clustering | Gamma';...
    'Opt vs Below | Global efficiency | Theta';...
    'Opt vs Below | Global efficiency | Alpha';...
    'Opt vs Below | Global efficiency | Beta';...
    'Opt vs Below | Global efficiency | Gamma';...
    'Opt vs Below | Centrality | Theta';...
    'Opt vs Below | Centrality | Alpha';...
    'Opt vs Below | Centrality | Beta';...
    'Opt vs Below | Centrality | Gamma';...
    'Opt vs Below | Participation coefficient | Theta';...
    'Opt vs Below | Participation coefficient | Alpha';...
    'Opt vs Below | Participation coefficient | Beta';...
    'Opt vs Below | Participation coefficient | Gamma';...
    'Opt vs Below | Degree | Theta';...
    'Opt vs Below | Degree | Alpha';...
    'Opt vs Below | Degree | Beta';...
    'Opt vs Below | Degree | Gamma';...

    'Opt vs Above | Clustering | Theta';...
    'Opt vs Above | Clustering | Alpha';...
    'Opt vs Above | Clustering | Beta';...
    'Opt vs Above | Clustering | Gamma';...
    'Opt vs Above | Global efficiency | Theta';...
    'Opt vs Above | Global efficiency | Alpha';...
    'Opt vs Above | Global efficiency | Beta';...
    'Opt vs Above | Global efficiency | Gamma';...
    'Opt vs Above | Centrality | Theta';...
    'Opt vs Above | Centrality | Alpha';...
    'Opt vs Above | Centrality | Beta';...
    'Opt vs Above | Centrality | Gamma';...
    'Opt vs Above | Participation coefficient | Theta';...
    'Opt vs Above | Participation coefficient | Alpha';...
    'Opt vs Above | Participation coefficient | Beta';...
    'Opt vs Above | Participation coefficient | Gamma';...
    'Opt vs Above | Degree | Theta';...
    'Opt vs Above | Degree | Alpha';...
    'Opt vs Above | Degree | Beta';...
    'Opt vs Above | Degree | Gamma';...
    };

% Get the scale (absmax) for each comparison
bars = max(abs(squeeze(statvalues(:,3,:))));

% creating 64 absmax values based on comparison between relevant combos
max_to_set = [...
    max([bars(1), bars(21)]);...
    max([bars(2), bars(22)]);...
    max([bars(3), bars(23)]);...
    max([bars(4), bars(24)]);...
    
    max([bars(5), bars(25)]);...
    max([bars(6), bars(26)]);...
    max([bars(7), bars(27)]);...
    max([bars(8), bars(28)]);...
    
    max([bars(9), bars(29)]);...
    max([bars(10), bars(30)]);...
    max([bars(11), bars(31)]);...
    max([bars(12), bars(32)]);...
    
    max([bars(13), bars(33)]);...
    max([bars(14), bars(34)]);...
    max([bars(15), bars(35)]);...
    max([bars(16), bars(36)]);...
    
    max([bars(17), bars(37)]);...
    max([bars(18), bars(38)]);...
    max([bars(19), bars(39)]);...
    max([bars(20), bars(40)]);...
    
    
    max([bars(1), bars(21)]);...
    max([bars(2), bars(22)]);...
    max([bars(3), bars(23)]);...
    max([bars(4), bars(24)]);...
    
    max([bars(5), bars(25)]);...
    max([bars(6), bars(26)]);...
    max([bars(7), bars(27)]);...
    max([bars(8), bars(28)]);...
    
    max([bars(9), bars(29)]);...
    max([bars(10), bars(30)]);...
    max([bars(11), bars(31)]);...
    max([bars(12), bars(32)]);...
    
    max([bars(13), bars(33)]);...
    max([bars(14), bars(34)]);...
    max([bars(15), bars(35)]);...
    max([bars(16), bars(36)]);...
    
    max([bars(17), bars(37)]);...
    max([bars(18), bars(38)]);...
    max([bars(19), bars(39)]);...
    max([bars(20), bars(40)]);

];

%% Plot only the t map with significant electrodes as big dots
statparams = {'value1','value2','tvalue','tfce','pvalue'};

for comparn_no = 1:size(condnlist,1)
    fid = figure('Position',[100 100 800 600]);
%     sgtitle(sprintf('%s\n', cell2mat(condnlist(comparn_no))), 'FontSize', 16, 'Color', '#CD5C5C');

    tmapmax = max_to_set(comparn_no);  
    tmapmin = -1 *max_to_set(comparn_no); 

    topoplot(squeeze(statvalues(:,3,comparn_no)),chanlocs_55,...
        'maplimits',[tmapmin,tmapmax],...
        'emarker2',{find(squeeze(statvalues(:,5,comparn_no))<0.05),'.','1, 1, 1',30});
    title(statparams(3));

    % Customize the plot to remove contour lines
    h = gca; % Get the handle of the current axes
    contour_handle = findobj(h.Children, 'Type', 'Contour'); % Find the contour lines
    set(contour_handle, 'LineColor', 'none');
    % You can also set the contour line color to match the background color if needed:
    % set(contour_handle, 'LineColor', get(gca, 'Color'));

    % Get the handle to the color bar
    cbar_handle = cbar;

    % Adjust the colorbar position (% from left edge, % from bottom, % of figure width, % of figure height)
    cbar_handle.Position = [0.85, 0.125, 0.03, 0.8];

    % Set the font size for the color bar
    cbar_handle.FontSize = 20;  % Replace 14 with your desired font size

    fname = strcat(strrep(cell2mat(condnlist(comparn_no)), ' | ', '_'), '.png');
    exportgraphics(fid,fname,...
        'BackgroundColor', '#fbf7d1',...
        'Resolution', 600);
    close(fid);
end