%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Topomaps statistics for graph theory measures using LIMO toolbox
% 1. Load the master matrix
% 2. Get the list of comparisons
% 3. Get the significance, effect sizes etc

% author @ Rahul Venugopal on 25th July 2023
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Load the master data mat file
load 'results_GT_LIMO.mat';
% The order of first dimension is as follows
% BW pre, BW post, Gamma pre, Gamma post, Theta pre, Theta post

% Load the chanlocs file
load chanlocs_55.mat;

% Comparison list | 1st and 2nd index are for 1st and second indices of data
comparn_list_values = [...
    1,2,1,1;...
    1,2,1,2;...
    1,2,1,3;...
    1,2,1,4;...
    1,2,2,1;...
    1,2,2,2;...
    1,2,2,3;...
    1,2,2,4;...
    1,2,3,1;...
    1,2,3,2;...
    1,2,3,3;...
    1,2,3,4;...
    1,2,4,1;...
    1,2,4,2;...
    1,2,4,3;...
    1,2,4,4;...
    1,2,5,1;...
    1,2,5,2;...
    1,2,5,3;...
    1,2,5,4;...

    3,4,1,1;...
    3,4,1,2;...
    3,4,1,3;...
    3,4,1,4;...
    3,4,2,1;...
    3,4,2,2;...
    3,4,2,3;...
    3,4,2,4;...
    3,4,3,1;...
    3,4,3,2;...
    3,4,3,3;...
    3,4,3,4;...
    3,4,4,1;...
    3,4,4,2;...
    3,4,4,3;...
    3,4,4,4;...
    3,4,5,1;...
    3,4,5,2;...
    3,4,5,3;...
    3,4,5,4;...

    5,6,1,1;...
    5,6,1,2;...
    5,6,1,3;...
    5,6,1,4;...
    5,6,2,1;...
    5,6,2,2;...
    5,6,2,3;...
    5,6,2,4;...
    5,6,3,1;...
    5,6,3,2;...
    5,6,3,3;...
    5,6,3,4;...
    5,6,4,1;...
    5,6,4,2;...
    5,6,4,3;...
    5,6,4,4;...
    5,6,5,1;...
    5,6,5,2;...
    5,6,5,3;...
    5,6,5,4;...
    ];

condnlist  = {...
    'BW | Clustering | Theta';...
    'BW | Clustering | Alpha';...
    'BW | Clustering | Beta';...
    'BW | Clustering | Gamma';...
    'BW | Global efficiency | Theta';...
    'BW | Global efficiency | Alpha';...
    'BW | Global efficiency | Beta';...
    'BW | Global efficiency | Gamma';...
    'BW | Centrality | Theta';...
    'BW | Centrality | Alpha';...
    'BW | Centrality | Beta';...
    'BW | Centrality | Gamma';...
    'BW | Participation coefficient | Theta';...
    'BW | Participation coefficient | Alpha';...
    'BW | Participation coefficient | Beta';...
    'BW | Participation coefficient | Gamma';...
    'BW | Degree | Theta';...
    'BW | Degree | Alpha';...
    'BW | Degree | Beta';...
    'BW | Degree | Gamma';...

    'Gamma | Clustering | Theta';...
    'Gamma | Clustering | Alpha';...
    'Gamma | Clustering | Beta';...
    'Gamma | Clustering | Gamma';...
    'Gamma | Global efficiency | Theta';...
    'Gamma | Global efficiency | Alpha';...
    'Gamma | Global efficiency | Beta';...
    'Gamma | Global efficiency | Gamma';...
    'Gamma | Centrality | Theta';...
    'Gamma | Centrality | Alpha';...
    'Gamma | Centrality | Beta';...
    'Gamma | Centrality | Gamma';...
    'Gamma | Participation coefficient | Theta';...
    'Gamma | Participation coefficient | Alpha';...
    'Gamma | Participation coefficient | Beta';...
    'Gamma | Participation coefficient | Gamma';...
    'Gamma | Degree | Theta';...
    'Gamma | Degree | Alpha';...
    'Gamma | Degree | Beta';...
    'Gamma | Degree | Gamma';...

    'Theta | Clustering | Theta';...
    'Theta | Clustering | Alpha';...
    'Theta | Clustering | Beta';...
    'Theta | Clustering | Gamma';...
    'Theta | Global efficiency | Theta';...
    'Theta | Global efficiency | Alpha';...
    'Theta | Global efficiency | Beta';...
    'Theta | Global efficiency | Gamma';...
    'Theta | Centrality | Theta';...
    'Theta | Centrality | Alpha';...
    'Theta | Centrality | Beta';...
    'Theta | Centrality | Gamma';...
    'Theta | Participation coefficient | Theta';...
    'Theta | Participation coefficient | Alpha';...
    'Theta | Participation coefficient | Beta';...
    'Theta | Participation coefficient | Gamma';...
    'Theta | Degree | Theta';...
    'Theta | Degree | Alpha';...
    'Theta | Degree | Beta';...
    'Theta | Degree | Gamma';
    };

% Set the color map using Behinger's palette
colormap_7 = cmap_rdylbu(7);
colormap_5 = cmap_rdylbu(5);

%% Compute
% Initialise statsvalues from TFCE
statparams = {'value1','value2','tvalue','tfce','pvalue'};
statvalues = zeros(length(chanlocs_55),length(statparams), size(comparn_list_values,1));

% Select the threshold
th = 29;
data = squeeze(opt_master_conditions(:,:,th,:,:,:));

% Looping through each comparison
for comparn_no = 1:size(comparn_list_values,1)

    param_no = comparn_list_values(comparn_no,3);
    band = comparn_list_values(comparn_no,4);

    group_1 = comparn_list_values(comparn_no,1);
    group_2 = comparn_list_values(comparn_no,2);
    
    % we are flipping dimensions for value1 and value2 because LIMO needs chans*samples
    value1 = transpose(squeeze(data(group_1, param_no, band, :, :)));
    value2 = transpose(squeeze(data(group_2,  param_no, band, :, :)));
    
    % two conditions to compare chans*subj | 500 is boots | 3 is for paired
    % t test | 0.5 is for the neighbour distance. This was computed
    % iteratively and manually verified to include neighbours based on
    % topomap provided by Brain products using find_my_neighbour_dist.m

    limoresults = accs_limostats_robustttest(value1, value2, chanlocs_55, 5000, 3, 0.5);

    statvalues(:,1,comparn_no) = trimmean(value1, 20, 2);
    statvalues(:,2,comparn_no) = trimmean(value2, 20, 2);

    statvalues(:,3,comparn_no) = limoresults.tvalue;    
    statvalues(:,4,comparn_no) = limoresults.tfce_score;
    statvalues(:,5,comparn_no) = limoresults.pvalue;
end

% Save the stats values
save('robust_t_paired.mat', 'statvalues');
%% Plot only the t map with significant electrodes as big dots

for comparn_no = 1:size(condnlist,1)
    fid = figure('Position',[100 100 500 500]);
    sgtitle(sprintf('%s\n', cell2mat(condnlist(comparn_no))), 'FontSize', 16, 'Color', '#CD5C5C');

    tmapmax = max(statvalues(:,3,comparn_no));   
    tmapmin = min(statvalues(:,3,comparn_no));   

    topoplot(squeeze(statvalues(:,3,comparn_no)),chanlocs_55,...
        'maplimits',[tmapmin,tmapmax],...
        'emarker2',{find(squeeze(statvalues(:,5,comparn_no))<0.05),'.','1, 1, 1',30});
    title(statparams(3));

    % Customize the plot to remove contour lines
    h = gca; % Get the handle of the current axes
    contour_handle = findobj(h.Children, 'Type', 'Contour'); % Find the contour lines
    set(contour_handle, 'LineColor', 'none');
    % You can also set the contour line color to match the background color if needed:
    % set(contour_handle, 'LineColor', get(gca, 'Color'));
    cbar;

    fname = strcat(strrep(cell2mat(condnlist(comparn_no)), ' | ', '_'), '.png');
    exportgraphics(fid,fname,...
        'Resolution', 600);
    close(fid);
end

%% Plot template full
for comparn_no = 1:size(condnlist,1)

    % Generate a blank plot and add a title    
    fid = figure('Position',[160 100 1600 400]);
    nrows = 1;
    ncols = length(statparams)-1;
    sgtitle(sprintf('%s', cell2mat(condnlist(comparn_no))), 'FontSize', 16, 'Color', '#CD5C5C');
    
    plotmin = min(statvalues(:,1:2,comparn_no),[],'all');
    plotmax = max(statvalues(:,1:2,comparn_no),[],'all');
    tmapmax = max(abs(statvalues(:,3,comparn_no)),[],'all');   
    
    subplot(nrows,ncols, 1);
    topoplot(squeeze(statvalues(:,1, comparn_no)),chanlocs_55,...
        'colormap', cmap_rdylbu(5),...
        'maplimits',[plotmin,plotmax]);
    cbar;

    subplot(nrows,ncols,2);
    topoplot(squeeze(statvalues(:,2, comparn_no)),chanlocs_55,...
        'colormap', cmap_rdylbu(5),...
        'maplimits',[plotmin,plotmax]);
    cbar;

    subplot(nrows,ncols,3);
    topoplot(squeeze(statvalues(:,3,comparn_no)),chanlocs_55,...
        'colormap', cmap_rdylbu(5),...
        'maplimits',[-tmapmax,tmapmax],...
        'emarker2',{find(squeeze(statvalues(:,5,comparn_no))<0.05),'.','0, 0, 0',30,10});
    title(statparams(3));
    cbar;

    plot_id2 = subplot(nrows,ncols,4);
    topoplot(squeeze(statvalues(:,5,comparn_no)),chanlocs_55,...
        'colormap', cmap_rdylbu(3),...
        'maplimits',[0 0.2]);
    title(statparams(5));
    cbar;
    
    fname = strcat(cell2mat(condnlist(comparn_no)), '.png');
    exportgraphics(fid,fname,...
        'Resolution', 600);
    close(fid);
end